version: '3.8'

services:
  # MobSF сервер
  mobsf:
    image: opensecurity/mobile-security-framework-mobsf:latest
    ports:
      - "9001:8000"
    volumes:
      - mobsf_data:/home/mobsf/.MobSF
      - ./source:/home/mobsf/uploads
      - ../src:/home/mobsf/src
    environment:
      - MOBSF_API_KEY=b0d4bff3ceeeb37fd673827dcf7c2f510fcb40a875d0cbf7635dfe6c1d7bf5d5
    user: root
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mobsf_data:
    driver: local 