version: '3.8'

services:
  # MobSF сервер
  mobsf:
    image: opensecurity/mobile-security-framework-mobsf:latest
    ports:
      - "8003:8000"
    environment:
      - MOBSF_API_KEY=${MOBSF_API_KEY}
      - MOBSF_SKIP_CLEANUP=true
      - MOBSF_AUTO_SCAN=true
    volumes:
      - mobsf_data:/home/mobsf/.MobSF
      - ./apk:/home/mobsf/uploads:rw  # Добавляем права на запись
    user: root  # Запускаем от root для решения проблем с правами
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Сканер безопасности
  scanner:
    build: .
    volumes:
      - ./apk:/app/apk:rw  # Добавляем права на запись
      - ./results:/results:rw  # Добавляем права на запись
      - ./reports:/app/reports:rw  # Добавляем права на запись
    environment:
      - MOBSF_API_KEY=${MOBSF_API_KEY}
      - MOBSF_HOST=http://mobsf:8000
      - SCAN_MODE=auto  # Автоматический режим сканирования
      - REPORT_TYPE=all  # Генерировать все типы отчетов
    depends_on:
      mobsf:
        condition: service_healthy
    command: ["python", "main.py", "--auto-scan"]

volumes:
  mobsf_data:
    driver: local 